export const ZAMBOANGA_BARANGAYS = [
  "Arena Blanco",
  "Ayala",
  "Bagong Calarian",
  "Baliwasan",
  "Baluno",
  "Boalan",
  "Bolong",
  "Buenavista",
  "Bunguiao",
  "Busay",
  "Cabaluay",
  "Cabatangan",
  "Cacao",
  "Calabasa",
  "Calarian",
  "Camino Nuevo",
  "Campo Islam",
  "Canelar",
  "Capisan",
  "Cawit",
  "Culianan",
  "Curuan",
  "Dita",
  "Divisoria",
  "Dulian (Upper Bunguiao)",
  "Dulian (Upper Pasonanca)",
  "Dumagsa",
  "Guisao",
  "Guiwan",
  "Kasanyangan",
  "La Paz",
  "Labuan",
  "Lamisahan",
  "Landang Gua",
  "Landang Laum",
  "Lanzones",
  "Lapakan",
  "Latuan",
  "Licomo",
  "Limaong",
  "Limpapa",
  "Lubigan",
  "Lumayang",
  "Lumbangan",
  "Lunzuran",
  "Maasin",
  "Malagutay",
  "Mampang",
  "Manalipa",
  "Mangusu",
  "Manicahan",
  "Mariki",
  "Mercedes",
  "Muti",
  "Pamucutan",
  "Pangapuyan",
  "Panubigan",
  "Pasilmanta",
  "Pasobolong",
  "Pasonanca",
  "Patalon",
  "Putik",
  "Quiniput",
  "Recodo",
  "Rio Hondo",
  "Salaan",
  "San Jose Cawa-Cawa",
  "San Jose Gusu",
  "San Roque",
  "Sangali",
  "Santa Barbara",
  "Santa Catalina",
  "Santa Maria",
  "Santo Niño",
  "Sibulao",
  "Sinubung",
  "Sinunuc",
  "Tagasilay",
  "Taguiti",
  "Talabaan",
  "Talisayan",
  "Talon-Talon",
  "Taluksangay",
  "Tetuan",
  "Tictabon",
  "Tictapul",
  "Tigbalabag",
  "Tolosa",
  "Tugbungan",
  "Tulungatung",
  "Tumaga",
  "Tumalutap",
  "Tumitus",
  "Victoria",
  "Vitali",
  "Zambowood",
  "Zone I",
  "Zone II",
  "Zone III",
  "Zone IV"
];
